version: "3.9"

services:

  postgres:
    image: postgres:14.2
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports: 
      - '5432:5432'
    volumes:
      - album-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - album-redis:/var/lib/redis/data

  album:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./album:/opt/app
    links:
      - postgres
      - redis
      - chrome-server
    ports:
      - '3000:3000'
    env_file:
      - ./.env

  chrome-server:
    image: selenium/standalone-chrome:96.0
    ports:
      - "4444:4444"

volumes:
  album-postgres:
  album-redis: